image: maven:3.6-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.artifact.threads=50"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn clean $MAVEN_CLI_OPTS $MAVEN_OPTS install -DskipTests

test:
  stage: test
  script:
    - mvn test
